### ISSUE TITLE
Error launching the application

### ISSUE THREAD

**Issue by feeef** [jacquetc/plume-creator#5]
Thank you for making this great software!

I am trying to run the alpha version on my Debian box using Gnome Shell, but with no success.

I have installed the required libraries, defined my environment variable, following your instructions but there is nothing about compiling and launching the application on Linux so I tried to follow the Windows instructions.
I made src/plume/plume.py executable and tried to run it. It didn't launch and I got the following error : 

from: can't read /var/mail/PyQt5.Qt
from: can't read /var/mail/core.core
from: can't read /var/mail/data.database
./plume.py: line 8: syntax error near unexpected token `('
./plume.py: line 8: `def launch_gui(core):'

I may have missed something...

Thank you very much for your help!

**Comment by jwvdveen** [comment]
Hi,

Which Linux do you use? **Sorry, you are using Debian. Did not noticed it on my smartphone.**
Which version of PyQt do you have installed? **Debian doesn't have PyQt5.4 in the repository, so you have to build that yourself.**
And how exactly do you execute Plume? **On Debian you have to use "python3 path/to/plume.py"**

Perhaps we can pinpoint the problem.

Regards,
Jan-Willem

**Comment by feeef** [comment]
Thanks for your reply!

I am using Debian Testing (Stretch) with python3-pyqt5 v5.6

I have set PLUME_DEVELOP_FROM to point to my plume-creator folder in my .bashrc file.

To start Plume I just do : 
$ cd src/plume/
$ ./plume.py

**Comment by jwvdveen** [comment]
Could you do something like `$ python3 plume.py`?
And I'm a bit confused about the `/var/mail/PyQt5.Qt` etc. Why is everything pointing to `/var/mail/`?

**Comment by feeef** [comment]
`$ python3 plume.py` did the trick thank you! :)
I don't get anymore error when launching the app. the /var/mail/ error has gone as well.

I close the issue.
